[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "archi_reports"
version = "0.1.0"
description = "Archimate reports generator"
requires-python = ">=3.8"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
testpaths = [
    "tests",
]